[package]
name = "omniuil_verifier"
version = "0.1.0"
edition = "2021"

[lib]
name = "verifier"
path = "src/lib.rs"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_cbor = "0.11"
serde_bytes = "0.11"
thiserror = "1.0"
sha2 = "0.10"

ed25519-dalek = { version = "2.1", features = ["std"] }
rand = "0.8"
