mod commands;
mod semantic_demo;

use clap::{Parser, Subcommand};
use std::path::PathBuf;

use commands::scan;
use omniuil_core::integrations::github_pr::GitHubPr;

#[derive(Parser)]
#[command(
    name = "omnishield",
    version = "0.5.0",
    about = "OmniShield AI - Autonomous Application Security Engine"
)]
struct Cli {
    #[command(subcommand)]
    command: Option<Commands>,

    #[arg(long)]
    semantic_demo: bool,
}

#[derive(Subcommand)]
enum Commands {
    Scan {
        path: PathBuf,

        #[arg(long)]
        push_check: bool,

        #[arg(long)]
        pr_review: bool,
    },

    CreatePr,
}

fn main() {
    let cli = Cli::parse();

    if cli.semantic_demo {
        semantic_demo::run_semantic_demo();
        return;
    }

    match cli.command {
        Some(Commands::Scan {
            path,
            push_check,
            pr_review,
        }) => {
            println!();
            println!("====================================");
            println!(" OmniShield AI Security Scanner v0.5.0");
            println!("====================================");
            println!();

            scan::run(path, None, None);

            if push_check {
                println!("GitHub push check enabled.");
            }

            if pr_review {
                println!("GitHub PR review enabled.");
            }
        }

        Some(Commands::CreatePr) => {
            let repo_owner = std::env::var("GITHUB_REPO_OWNER").expect("Missing GITHUB_REPO_OWNER");

            let repo_name = std::env::var("GITHUB_REPO_NAME").expect("Missing GITHUB_REPO_NAME");

            let token = std::env::var("GITHUB_TOKEN").expect("Missing GITHUB_TOKEN");

            let pr = GitHubPr::create_pull_request(
                &repo_owner,
                &repo_name,
                &token,
                "test-scan",
                "main",
                "OmniShield AI Security Review",
                "Automated security analysis generated by OmniShield AI",
            );

            println!("PR result: {:?}", pr);
        }

        None => {
            println!("Usage:");
            println!("  omnishield scan <path>");
            println!("  omnishield scan <path> --pr-review");
            println!("  omnishield scan <path> --push-check");
        }
    }
}
