mod semantic_demo;
use omniuil_core::integrations::github_pr::GitHubPr;
use std::env;

use omniuil_core::integrations::github_api::GitHubApiClient;
use omniuil_core::integrations::github_review::GitHubReviewClient;
use omniuil_core::runtime::executor::RuntimeExecutor;

fn main() {
    let args: Vec<String> = std::env::args().collect();

    if args.iter().any(|arg| arg == "--semantic-demo") {
        semantic_demo::run_semantic_demo();
        return;
    }

    if args.contains(&"--create-pr".to_string()) {
        let repo_owner = std::env::var("GITHUB_REPO_OWNER").unwrap();

        let repo_name = std::env::var("GITHUB_REPO_NAME").unwrap();

        let github_token = std::env::var("GITHUB_TOKEN").unwrap();

        let pr_number = GitHubPr::create_pull_request(
            &repo_owner,
            &repo_name,
            &github_token,
            "test-scan",
            "main",
            "OmniUil Automated Security PR",
            "Automated security review generated by OmniUil AI",
        )
        .unwrap();

        println!("PR created successfully: #{}", pr_number);

        return;
    }

    let args: Vec<String> = env::args().collect();

    if args.len() < 2 {
        println!("Usage: cli <target_path> [--push-check] [--pr-review]");
        return;
    }

    let target_path = &args[1];

    let github_push_check = args.iter().any(|a| a == "--push-check");
    let github_pr = args.iter().any(|a| a == "--pr-review");

    let findings = RuntimeExecutor::execute(target_path);

    println!("Scan complete.");
    println!("Total findings: {}", findings.len());
    println!();

    for finding in &findings {
        println!(
            "[{}] {}:{} - {} ({})",
            finding.severity, finding.file, finding.line, finding.title, finding.id
        );
    }

    if github_push_check {
        let repo_owner = env::var("GITHUB_REPO_OWNER").expect("Missing GITHUB_REPO_OWNER");

        let repo_name = env::var("GITHUB_REPO_NAME").expect("Missing GITHUB_REPO_NAME");

        let commit_sha = env::var("GITHUB_COMMIT_SHA").expect("Missing GITHUB_COMMIT_SHA");

        let github_token = env::var("GITHUB_TOKEN").expect("Missing GITHUB_TOKEN");

        GitHubApiClient::create_commit_status(
            &repo_owner,
            &repo_name,
            &commit_sha,
            &github_token,
            "Security scan completed",
            if findings.is_empty() {
                "success"
            } else {
                "failure"
            },
        )
        .unwrap();

        println!("GitHub Commit Status pushed successfully.");
    }

    if github_pr {
        let repo_owner = env::var("GITHUB_REPO_OWNER").expect("Missing GITHUB_REPO_OWNER");

        let repo_name = env::var("GITHUB_REPO_NAME").expect("Missing GITHUB_REPO_NAME");

        let github_token = env::var("GITHUB_TOKEN").expect("Missing GITHUB_TOKEN");

        let pr_number: u64 = env::var("GITHUB_PR_NUMBER")
            .expect("Missing GITHUB_PR_NUMBER")
            .parse()
            .expect("Invalid GITHUB_PR_NUMBER");

        GitHubReviewClient::create_pr_review_comment(
            &repo_owner,
            &repo_name,
            pr_number,
            &github_token,
            "⚠ OmniUil detected security vulnerabilities in this Pull Request. Please review the findings before merging.",
        )
        .unwrap();

        println!("GitHub PR Review comment created successfully.");
    }
}
