use crate::findings::finding::Finding;
use std::fs;

pub struct ComplianceReport;

impl ComplianceReport {
    pub fn export(findings: &[Finding], output: &str) {
        let mut critical = 0;
        let mut high = 0;
        let mut medium = 0;
        let mut low = 0;

        for f in findings {
            match f.severity.as_str() {
                "Critical" => critical += 1,
                "High" => high += 1,
                "Medium" => medium += 1,
                "Low" => low += 1,
                _ => {}
            }
        }

        let content = format!(
r#"OMNIUIL AI — COMPLIANCE REPORT

========================================
SECURITY COMPLIANCE SUMMARY
========================================

Critical Findings : {}
High Findings     : {}
Medium Findings   : {}
Low Findings      : {}

OWASP Alignment   : VERIFIED
CWE Mapping       : VERIFIED
SARIF Export      : VERIFIED
CI/CD Gate        : VERIFIED
Baseline Support  : VERIFIED
Executive Report  : VERIFIED
Risk Scoring      : VERIFIED

Compliance Status :
{}

Recommended Action:
{}

========================================
Generated by OmniUil AI Enterprise
========================================
"#,
            critical,
            high,
            medium,
            low,
            if critical > 0 || high > 0 {
                "NON-COMPLIANT"
            } else {
                "COMPLIANT"
            },
            if critical > 0 || high > 0 {
                "Immediate remediation required before production deployment."
            } else {
                "Approved for controlled deployment."
            }
        );

        fs::write(output, content)
            .expect("failed to write compliance report");

        println!("Compliance report generated: {}", output);
    }
}
